remote-week2: Node.JS  APIs
raamiiChu/remote-assignments pull request #2
Opened 2023-10-06 10:05 UTC by raamiiChu

# AWS  
- Elastic IP Address: `52.192.99.138`  

- Database Name: `assignment`  

- Health Check API: http://52.192.99.138:3000/healthcheck  

---  

# Change Summary  
1. Add `remote-week2` folder  
    - `app.js`: Connect to the database with Node.JS    
    - `backup.sql`: Database backup file  

2. Add `appspec.yml` & `scripts` folder  
  For code deployment on AWS

---  

# Understanding Check  

### How did you design the user table schema? Why?  

```
create table `users`(
	id int PRIMARY KEY AUTO_INCREMENT,
	name varchar(32) NOT NULL,
	email varchar(64) NOT NULL UNIQUE,
	password varchar(64) NOT NULL,
	created_at datetime DEFAULT now()
);
```

- id: `PRIMARY KEY`, because each data should have one unique primary key to recognize it. Set it as `AUTO_INCREMENT` can make sure the value can auto-generated.   

- name: Can not be empty  

- email: Each email can only register one account, so I set it as `UNIQUE`  

- password: Can not be empty  

- created_at: Set its default value as current time  

---  

### What does the *Status Code* mean? Is it a must to use?  

**Status Code** is the number which is returned by the server to response the request of client. **Status Code** has 5 kinds, each represented by the first digit of the code:  

- 1XX: Informational  
- 2XX: Successful  
- 3XX: Redirection  
- 4XX: Client Error  
- 5XX: Server Error  

**State Code** provide a standard way to tranfer the result of a request, making it easier for developers to analyze and handle issues. Therefore, it's a fundamental part of the HTTP / HTTPS protocol. Must to use it when developing a web server or an API.  

---  

### How and what tools did you use to test your APIs?  

[**VS Code Thunder Client**](https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client)  
It's an extension in VS Code providing a easy way for developers to test their APIs without switch to other apps.    

![VS Code Thunder Client](https://github.com/raamiiChu/remote-assignments/assets/87169493/37ed0768-8601-41a8-958c-4385dd756084)

---  

### How and what tools did you use to make sure the app would not shut down even if you exit the ssh connection?  

I use CodeDelpoy & CodePipeline in AWS to deploy the code automatically, the method can make sure the app would not shut down even if exiting the ssh connection. As for `.env` file, I choose to upload it manually, due to its sensitive info.  

[**Details**](https://www.notion.so/Code-Deployment-91a5ec6e84744ddaa1773001523586e6?pvs=4)

---  

### What are the interactions between client, firewall, EC2 and RDS when you send a request to you app server and get the response? You can use sequence diagram to describe it more clearly.  

---

### ( Advanced Optional ) What did you do to make clients access your APIs without the certain port number?

Just Change the port number to 80 / 443, beacuse it's the default port number of HTTP / HTTPS. 

p.s. I do not push the code to GitHub

```
const app = express();
const port = 80;
```

**Connect without port number**
![Connect without port number](https://github.com/raamiiChu/remote-assignments/assets/87169493/daf318e3-e36c-419f-9745-af70929c495d)

---  

### ( Advanced Optional ) Compare to the application server, what's the web server?

- Web Server
    Handle HTTP / HTTPS requests and responses. It serves static content, such as HTML, CSS, images, etc.

- Application Server
    Execute dynamic content and application functionality. It handles dynamic tasks, such as database interactions, user authentication, etc.

---

2023-10-07 08:57 UTC, addie-tyc requested changes
code 的部分沒有問題，但剛剛檢測 API 到一半突然連 healthcheck 都沒打過？
部署的部分其實我沒有用過 codePipeline，要注意免費用量喔！

2023-10-07 08:57 UTC, addie-tyc commented on remote-week2/app.js
> +const bodyParser = require("body-parser");
Express 4.18 以後還有需要引入 body-parser 嗎？

2023-10-07 08:57 UTC, addie-tyc commented on remote-week2/app.js
> +});
其實文件中 Request-Date 會由 client 帶進去，用 middleware 和題意稍有不同，
content-type 的部分通常會由 client 指定，後端 server 會負責驗證這個請求是否需要被處理

2023-10-07 08:57 UTC, addie-tyc commented on remote-week2/app.js
> +        });
用 .env 滿好的！

2023-10-08 03:35 UTC, raamiiChu commented on remote-week2/app.js
> +const bodyParser = require("body-parser");
新版直接用 express 內建的函式即可

```
app.use(express.json());
```

2023-10-08 06:44 UTC, raamiiChu commented on remote-week2/app.js
> +});
程式碼保留（經過測試，註解程式碼後若格式撰寫正確，能完成題目原先要求）

- Content-Type
![Content-Type](https://github.com/raamiiChu/remote-assignments/assets/87169493/699c5879-dd79-4808-94f6-86378d17044d)

- Request-Date
```
var currentDate = new Date().toUTCString();
pm.request.headers.add({ key: 'request-date', value: currentDate });
```
![request-date](https://github.com/raamiiChu/remote-assignments/assets/87169493/fc2ffaaa-3783-4c06-b842-e51c37fb3334)

2023-10-08 14:43 UTC, addie-tyc approved these changes
LGTM. 有 hash 不錯

2023-10-08 14:44 UTC, addie-tyc approved these changes
LGTM

2023-10-08 15:35 UTC, merged